### ISSUE TITLE
AccesDenied with new version

### ISSUE THREAD

**Issue by aleon68** [appleboy/lambda-action#15] opened 2020-10-24 04:59 UTC
2020/10/24 03:39:22 AccessDeniedException: 
	status code: 403, request id: 88525d89-5162-461c-9df0-751443ef394b
2020/10/24 03:39:22 AccessDeniedException: 
	status code: 403, request id: 88525d89-5162-461c-9df0-751443ef394b

This issue without any change on template

**Comment by appleboy** [comment] 2020-10-24 06:34
I will take it

**Comment by appleboy** [comment] 2020-10-24 06:34
duplicate of https://github.com/appleboy/lambda-action/issues/14

**Closed by appleboy** 2020-10-24 06:34 UTC
